// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXliSSLhxv7ez-RmkFPqDPNEDnRaJuxcQ',
    appId: '1:1000144147169:web:fe1e383d2131739db39da0',
    messagingSenderId: '1000144147169',
    projectId: 'contactmanager-cda5e',
    authDomain: 'contactmanager-cda5e.firebaseapp.com',
    storageBucket: 'contactmanager-cda5e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlpdq-YI4rD9a2I9LyGOdM2mbheIG3wrw',
    appId: '1:1000144147169:android:dce6a00d2bf37d1ab39da0',
    messagingSenderId: '1000144147169',
    projectId: 'contactmanager-cda5e',
    storageBucket: 'contactmanager-cda5e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxoH2dsAV5CzdKVsamjteNxw7RK0zwwWc',
    appId: '1:1000144147169:ios:ec75b381fc17c122b39da0',
    messagingSenderId: '1000144147169',
    projectId: 'contactmanager-cda5e',
    storageBucket: 'contactmanager-cda5e.appspot.com',
    iosBundleId: 'com.example.contactManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxoH2dsAV5CzdKVsamjteNxw7RK0zwwWc',
    appId: '1:1000144147169:ios:ec75b381fc17c122b39da0',
    messagingSenderId: '1000144147169',
    projectId: 'contactmanager-cda5e',
    storageBucket: 'contactmanager-cda5e.appspot.com',
    iosBundleId: 'com.example.contactManager',
  );
}
